# Generated by Django 3.0.7 on 2020-06-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral_bloom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covid',
            new_name='State',
        ),
    ]
