# Generated by Django 3.0.7 on 2020-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_bloom', '0002_auto_20200626_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDataByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('positive', models.CharField(max_length=100)),
                ('death', models.CharField(max_length=100)),
                ('recovered', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
